apiVersion: v1
kind: PersistentVolume
metadata:
  name: dnetweb-mysql
  labels:
    name: dnetweb-mysql # name can be anything
spec:
  storageClassName: dnetweb-mysql # same storage class as pvc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.5.65 # NFS server IP address 
    path: "/Public/k8s_storage/dnetwebmysql/mysql1"   # NFS share location

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dnetweb-mysql2
  labels:
    name: dnetweb-mysql2 # name can be anything
spec:
  storageClassName: dnetweb-mysql # same storage class as pvc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.5.65 # NFS server IP address 
    path: "/Public/k8s_storage/dnetwebmysql/mysql2"   # NFS share location

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dnetweb-mysql3
  labels:
    name: dnetweb-mysql3 # name can be anything
spec:
  storageClassName: dnetweb-mysql # same storage class as pvc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.5.65 # NFS server IP address 
    path: "/Public/k8s_storage/dnetwebmysql/mysql3"   # NFS share location



---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dnetweb-mysql4
  labels:
    name: dnetweb-mysql4 # name can be anything
spec:
  storageClassName: dnetweb-mysql # same storage class as pvc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.5.65 # NFS server IP address 
    path: "/Public/k8s_storage/dnetwebmysql/mysql4"   # NFS share location